name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  automation-test-job:
    runs-on: ubuntu-latest
    name: Automation Test with Vitest and Cypress

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Unit Test with Vitest
        run: |
          yarn
          yarn test:unit

      - name: E2E Test with Cypress
        uses: cypress-io/github-action@v5
        with:
          start: yarn dev
